version: '2'
  
services:
    nextcloud:
        build: .
        container_name: nextcloud 
        restart: always
        ports: 
          - "80:80"
          - "443:443"
        volumes:
          - ./config:/var/www/nextcloud/config:rw
          - ./db:/var/lib/mysql:rw
          - ./data:/var/www/nextcloud/data:rw
