version: '3'

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --log-bin=mysqld-bin --binlog-format=ROW
    restart: on-failure
    volumes:
      - db:/var/lib/mysql
    env_file:
      - db.env

  redis:
    image: redis:alpine
    restart: on-failure

  app:
    build: ./app
    restart: on-failure
    volumes:
      - nextcloud:/var/www/html
      - /media/usb-nextcloud/nextcloud-data:/nextcloud-data
      - /media/usb-nextcloud/syncthing:/syncthing
    environment:
      - MYSQL_HOST=db
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_DATA_DIR=/nextcloud-data
    env_file:
      - db.env
    depends_on:
      - db
      - redis
        #    user: "1001:33"
                
  web:
    build: ./web
    restart: on-failure
    volumes:
      - nextcloud:/var/www/html:ro
    environment:
      - VIRTUAL_HOST=treso.redirectme.net
      - LETSENCRYPT_HOST=treso.redirectme.net
      - LETSENCRYPT_EMAIL=tras3@gmx.net
    depends_on:
      - app
    networks:
      - proxy-tier
      - default

  cron:
    build: ./app
    restart: on-failure
    volumes:
      - nextcloud:/var/www/html
      - /media/usb-nextcloud/nextcloud-data:/nextcloud-data
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  proxy:
    build: ./proxy
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: on-failure
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - VIRTUAL_HOST=treso.redirectme.net
    networks:
      - proxy-tier
    depends_on:
      - proxy

volumes:
  db:
  nextcloud:
  certs:
  vhost.d:
  html:

networks:
  proxy-tier:
